run.sh, rust_rayon/Cargo.lock, rust_rayon/Cargo.toml, rust_rayon/src/main.rs
=> Moar SPEEEED

python/related.py, run.sh
8.1 -> 1.35 seconds, approximately, on M1.
=> Use indexes, heap-based top k for python as the other languages do

run.sh
This PR adds `-skip-unused` option for V program compilation. This will improve performance of the program removing a few arrays allocation and another operation that are not needed for the actual code to run. I don't think this is cheating since this flag will present by default once markused thing become more stable
=> Add `-skip-unused` for V program compilation

v/related.v
It turned out that in `-prod` C compiler already optimizes this to memset (I believe), so no unsafe shenanigans needed
=> V reset array instead of allocate new

readme.md
Node.js and Deno are JavaScript programming language runtimes, not languages in and of themselves.
=> Node.js and Deno are not a "Language"

dart/models.dart
The `late` keyword is not necessary for the `Post` class. `late` variables does also come with a runtime cost since Dart cannot be sure these variables are not `null` and will therefore need to insert a runtime check. So removing the `late` keyword should help on the performance. If not, at least the code gets cleaner.
Another improvement is not using the `.cast()` method on `List<dynamic>`. The `cast()` will add a lazy cast which means it does a casting every time we read from the returned lazy list. It is better to do all the casting in one iteration with `List.from`.
=> [Dart] Remove `late` in models.dart

js/related.js
`for..of` loops are usually faster than `Array.prototype` loops. I replaced the `Array.prototype` loops with `for..of` loops when you don't need to access the index.
On my computer for Node 20 it went from 124ms -> 85ms
https://github.com/jinyus/related_post_gen/assets/13814048/b516fd18-1dc5-4431-82af-35d1bdfba36a
=> Speed up JS implementation

dart/related.dart
Main changes: 
* Dart's AOT compiler looses track of concrete types when containers-containing-other-containers are involved, e.g. `Map<K, List<T>>` or `List<List<T>>`. This makes operations wither nested containers slower. To work-around this problem you can simply wrap a nested container into some unique class - this helps AOT compiler to realise what comes from the container.
* Iterable.fillRange is slow - manually inlining it helps (I will file a bug against Dart to fix this).
* `for-in` is better than `forEach` when concrete types are properly known to the compiler (see the first item)
* Rewrote computation of top 5 to avoid unnecessary allocations
=> Optimize Dart version

python/related_np.py
- don't create a big tag array to find unique tag list
- smaller dtype makes the matrix take 2x less memory, so it's faster (except on Windows)
- instead of iterating over every tag in the inner loop, iterate over post tags
Each change saves 15-25 ms.
=> Numpy optimizations

python/related_np.py, python/requirements.txt, run.sh
As not every post has every tag, the post-tag matrix is sparse (has many 0s). Matrix multiplication is faster if we rely on this.
1. moving from numpy to scipy processing jumps from 500-700 ms to 270-280 ms;
2. using internals of sparse array representation (Compressed Space Row), sorting for top5 wins additional 40ms;
commit | import | compile | input | process | output | total
-- | -- | -- | -- | -- | -- | --
0: copy numpy matrix… | 47.52±0.88 | 0.00±0 | 3.548±0.023 | 476.7±4.3 | 18.25±0.98 | 546.1±5.8
1: use scipy sparse … | 81.6±5.2 | 0.00±0 | 3.571±0.082 | 276.0±3.9 | 18.8±2.0 | 380.0±5.8
2: sort results dire… | 78.2±1.2 | 0.00±0 | 3.530±0.035 | 228.4±7.8 | 18.5±1.1 | 328.6±8.4
Should this stay a separate implementation (and have a new run.sh entry), or should it replace the Numpy …
=> Python: use scipy sparse array over numpy dense array

rust/Cargo.lock, rust/Cargo.toml, rust/src/main.rs, rust_con/Cargo.lock, rust_con/Cargo.toml, rust_con/src/main.rs
Rust:
changed String (SString) to Cow<'a,str>, should help cache locality / memory-size, memory allocation-pressure (for longer strings if any were present)
removed mini-alloc, as the only thing being allocated is the temporary vec, and since it's always the same size each iteration, it shouldn't have any difference how the allocator works.
changed usize to u32 (saw a few ms speedup; assume due to cache locality)
=> returned default malloc; replaced Cow

rust/Cargo.lock, rust/Cargo.toml, rust/src/main.rs, rust_con/Cargo.lock, rust_con/Cargo.toml, rust_con/src/main.rs
In no particular order
* Bring back `mimalloc` in both cases
* Bring back `smallstr` for ID and tags; it's faster than borrowing from the original JSON blob, presumably due to better cache locality
* Also port that optimization to `rust` (previously it was only used in `rust_con`)
* Once `compact_str` gets another release, it will provide a significant performance improvement over `smallstr`, but I don't expect pulling a dependency from github instead of crates.io is something you want
* Actually borrow titles
* Use `u16`s instead of `usize`s for post index and count (someone changed them to `u32`s earlier today)
* Use slices for references to strings and vecs
* Use thin LTO for `rust_con`; explicitly use fat for `rust`
* Mark trivial functions (`eq()`, `partial_cmp()`, and `cmp()` on …
=> Assorted improvements to Rust benchmarks

csharp/Program.cs
`Stopwatch` should be used when you want to accurately measure code execution — using `DateTime.Now` isn't recommended.
=> Use `Stopwatch` instead of `DateTime.Now` in the C# implementation

csharp/Program.cs
This is more of a stylistic change, but you actually didn't need to have a `Program` class with a `Main` method, it's redundant code and adds two unnecessary levels of indentation — C# 10 introduced top-level statements, eliminating the need for explicitly declaring these. The only thing is that the types need to come after the statements.
=> Use top-level statements in the C# implementation

nim/config.nims
I found that rust uses LTO. It would be good to enable it for other compiled languages too
=> [Nim] enable flto

nim/related.nimble, nim/src/related.nim
- it is known that sometimes programs without `main` has some optimizations problems: local boost ~-25%
- switched to xxhash, which is pretty the same like @PMunch did before, but on my local tests it was a hair faster
=> [Nim] main + switch to xxhash

nim/src/related.nim
Just switches to use the slightly faster XXH3 algorithm from xxhash.
=> Use the slightly faster XXH3

csharp/Program.cs, csharp/related.csproj, run.ps1, run.sh
- AOT compilation.
- ~tagMap initialization without copying collections again.~ Surprisingly, pushing to stack and then converting to array is faster than using List<int>
- Reduced dictionary lookups in the loop to single lookup.
- Removed required keyword (AOT JSON serialization doesn't build in .NET 7 with `required` keyword, this might be fixed in .NET 8). 
- changed structs to classes as structs are copy by value by default (improves performance in this case)
=> C# optimizations

fsharp/Program.fs
- Reuse the top5 array
- Reduce the size of taggedPostCount array using bytes since the number of tags is <=100
This gave me a small speed boost on my machine from ~20ms to ~17ms
I'm running an Intel 13900K
=> FSharp Reuse top5 array

julia/related.jl
Just removing the vector allocation from `SVector{topn}([posts[ix] for ix in maxn)])`. 
It defeats the purpose of using the `SVector` altogether.
Maybe this results in ~1ms gain - but it is more about the logic this round.
=> Removing unnecessary allocation (Julia)

.github/workflows/benchmark.yml, python/related.py, python/related_np.py, python/requirements.txt, python/timing.py, run.ps1, run.sh
why 3.11:
- much better python solution performance:
* from 3.4s https://github.com/fizmat/related_post_gen/actions/runs/6434908946/job/17475091343#step:23:34
* to 1.7s https://github.com/fizmat/related_post_gen/actions/runs/6435418827/job/17476643206#step:24:39
* on 3.10 the flat list approach(1e179d136d12f926048ccc24baf1ffd9deccc5ff) is barely an improvement (about 80ms, did not test on runner, tested on a local Linux machine)
- orjson has a weird effect in 3.10:
* on 3.10 for some reason orjson slows down python (not numpy) processing by the same 80ms (also did not test on runner, tested on a local Linux machine)
* on 3.11 orjson does not affect processing time
orjson also saves about 15ms on output (not very relevant with python, a little relevant with scipy, pretty relevant with …
=> use python 3.11 on runner

fsharp/Program.fs
- Profiling shows loop for counting related post counts is ~45% of the time
- Logic elides a bounds check in the hottest loop by returning a value by ref
- ~5% performance improvement on my machine
- Note, this is making the bounds check unnecessary, so it's not violating the rule that says you can't drop bounds checks
=> Elide bounds check

python/related_numba.py, python/related_numba_con.py, python/requirements.txt, run.sh
- a numpy solution not based on matrix multiplication, but adding arrays in a loop. Slower than the matrix solution, on par with the original Python solution: 1.5s processing, 1.5s total
- JIT compile the inner loop function with Numba: instantly overtake even scipy solution on processing: 140 ms processing, 650ms total (because of 180ms import and 310ms JIT compile)
- sorting to find top5 takes almost half the processing time. replace sorting with one pass over the array to save 55ms (*this part probably can be optimized*).
- other minor optimizations. Final: 60ms processing, 1.2s total (mostly compile)
- parallelize the outer loop: 27ms processing, 1.6s total (even longer compile)
Should the parallelized solution be a separate entry in run.sh?
It's not hard to use just one python script …
=> Numba (Python JIT compiler, a little cheating)

julia/related.jl
Two changes:
- Replace `haskey`, `d[k] = x` and `d[k]` with `get!` to cut down on code size and the number of required hashes. `get!` is a builtin function designed specifically for this common use case of getting an element from a dictionary or instantiating it if it's missing.
- Use an appropriately sized integer type for post index and counts. This will cause bugs if there are more than 2^16 posts. If that possibility for error is "cheating", we can add a near-zero-cost dispatch to dynamically determine the appropriate number type. I'd estimate that that dispatch will add about 6 lines of code, increase compilation time a bit, and not affect runtime at all.
=> Simplify and optimize Julia implementation

julia/related.jl
There was a local testing artefact left in the code (`@btime` usage for local benchmark).
Just removed it so this can work well when the benchmark is run.
=> Removed local benchmark (`@btime`) artefact

swift_con/Sources/main.swift
Not sure why this one got deleted. It's an official and stable library: https://github.com/apple/swift-collections, unlike what the rust_con is using with `rust_rayon v0.1.0`, which is now failing with `error[E0658]: use of unstable library feature 'local_key_cell_methods'` ;)
=> Bring back TreeDictionary

julia_con/related.jl
Julia is worried that `topn` might be mutated and so deoptimizes. The Julia people should really figure this out because there is literally only one assignment to `topn`, but whatever, moving the definition into the body of the loop speeds things up.
I also removed trailing whitespace.
=> [Julia] move `topn` definition into body of `@threads`

zig/main.zig
usize is inefficient whereas u8 is good enough for the case
=> fix zig memory usage

julia/related.jl, run.sh
it's possible my weird tweaking introduced performance degradation.
I don't fully understand Github CI environment, so let's revert it to be safe
=> Revert "formatting Julia and remove unnecessary deps"

csharp/Program.cs
Around 9% faster on my machine
```
dotnet publish -c Release
1..1000 | %{ measure-command { .\bin\release\net7.0\win-x64\native\related.exe } | % TotalMilliseconds } | measure -Average
```
- With `Fill(0)`: 79.4570753ms
- With `Clear()`: 86.0791141ms
=> [csharp] Changed Clear() to Fill(0)

.github/workflows/benchmark.yml, csharp/related.csproj, run.sh
While AOT finishes faster for the 5k entries JSON in the repo, it is not faster for larger sets, at least in .NET 7. Benchmark both flavors like for Java or Dart.
Things look different in .NET 8 (I see .NET 8 AOT matching Go speed) but the repo didn't update to .NET 8 yet. It could - .NET 8 RC2 is supported for use in production by Microsoft (marked [go-live](https://dotnet.microsoft.com/en-us/download/dotnet/8.0)).
=> Separate JIT and AOT configs for C#

js/related.js
Manually fill arrays as `Array.fill` is very slow in bun.
Thanks to @morkai for finding this.
=> Js manual fill

nim_con/.gitignore, nim_con/buildopt.sh, nim_con/config.nims, nim_con/related_con.nim, nim_con/related_con.nimble, nim_con/related_con/fixedtable.nim, run.sh
It works just fine, but performance relative to the single-threaded implementation seems to improve only with 8 or 16 cores/threads. I'll explain below, but for that reason I've made it a draft PR. If you're happy with it, feel free to take it out of draft and merge as is, and in any case I'll be working on improving the performance for 4 cores.
On my laptop with 16 cores and with 16/8 threads, I'm seeing processing times in the low teens. The numbers bounce around a bit across builds and runs, up into the 20-30 ms range, maybe owing to the inconsistent PGO discussed in #261 or maybe for some other reason/s. 
When I limit it to 4 threads, the performance is worse than the single-threaded Nim implementation. That's disappointing, but I'm optimistic there are ways to improve it.
---
With …
=> [Nim] concurrent

nim/.gitignore, nim/related.nimble, run.sh
Fixes #300 
On any machine where the environment isn't from scratch and builds/runs were being done without `-d`, after the changes in this PR it's recommended to do the following before the next build/run
```
$ rm -rf "${HOME}"/.nimble/pkgs2/related*
```
If using a custom `NIMBLE_DIR`, it would be:
```
$ rm -rf "${NIMBLE_DIR}"/pkgs2/related*
```
I made a few other small changes in this PR, each in their own commit.
=> [Nim] nimble flags

csharp/Program.cs, csharp/related.csproj
* Use `FrozenDictionary` to look up tags.
* Factor out `GetRelatedPost` so that we can use `stackalloc` that the compiler zero inits faster than what `Span.Clear` can do
* Add tight loop to find next highest `taggedPostCount`
* AOT only: [Optimize for speed](https://learn.microsoft.com/en-us/dotnet/core/deploying/native-aot/optimizing).
=> [Csharp] Use frozen dictionaries

run.sh
This stops an annoying warning from being printed when we use the `pkg` string macro instead of the `Pkg.activate` and `Pkg.instantiate` functions
=> tweak julia invocations

go/main.go, go_con/main.go
Main:
```
Go	| 24.25 ms | 374.70 ms | 3.28 s	
Go Concurrent | 13.31 ms | 166.98 ms | 1.42 s
```
This PR:
```
Go:                                                                                                                                                                                                                                            
Benchmark 1: ./related                                                                                                                                                                                                                 
Processing time (w/o IO): 24.189115ms …
```
=> [Go] Trigger GC Manually

nim/related.nimble
It is hard to find default `gcc` or `clang` versions on the runners. The PR could help with it a bit
=> echo gcc and clang versions

nim_con/buildopt.sh, nim_con/config.nims, nim_con/related_con.nim, run.sh
Here's a PR with ***only*** the `[Nim Con]` commits, i.e. affecting `nim_con` only, in case there's a hangup about the changes in `nim/` on `main` vs. `nim_rev` branches.
Will post fresh numbers from my Azure VM below. For `nim_con`, `nim_rev` consistently outperforms `main`, especially big differences for 20k and 60k runs.
=> [Nim Con] improve performance

csharp_con/Program.cs
We were allocating 3.5 GB of arrays. I'm seeing an 8% improvement, but it should ideally be measured on the benchmark machine because I wouldn't be too surprised if the OS was able to give out fresh zero initialized pages faster than we can zero them manually -  and this is not _too many_ individual allocations to garbage collect.
=> Limit allocations in concurrent C# impl

nim/config.nims, run.sh
Because `gcc` versions looks 2 years newer than clang during the run, I would suggest to check it again
=> [Nim] gcc again

nim_con/.gitignore, nim_con/build.sh, nim_con/buildopt.sh, nim_con/config.nims, nim_con/related_con.nim, nim_con/related_con.nimble, run.sh
Alternative to and closes #351.
Independent of the PGO work in open PR #351, I was able to make the `nim_com` implementation more efficient.
I also found that by switching from [`malebolgia`](https://github.com/Araq/malebolgia) to [`taskpools`](https://github.com/status-im/nim-taskpools), all available cores are better utilized[^1].
With these changes in `nim_con/related_con.nim`, clang or gcc PGO consistently decreases performance, so PGO is not used by default, i.e. `run.sh` invokes `nim_con/build.sh` instead of `nim_con/buildopt.sh`[^2].
With PGO ***not*** in the mix, the performance numbers seem to not bounce around too much.
For these changes, `gcc` builds perform better than `clang` builds.
It's now easy to switch compilers when invoking `build.sh` and `buildopt.sh`,  e.g. to use …
=> [Nim Con] switch to taskpools and general improvements

nim/src/related.nim
It was removed before, but different cc versions has different results
=> [Nim] avoid copy for related

nim/config.nims
The PR just to check only.
The reasons for it:
- Rust does not have the check in `release` mode at all
- Cpp does not have it at all
=> [Nim] test overflow checks disabled

cpp/main.cpp, cpp/main_con.cpp
nb: I see no difference on my machine.
before:
```
C++:
Benchmark 1: ./main
Processing time (w/o IO): 17 ms
Processing time (w/o IO): 17 ms
Processing time (w/o IO): 16 ms
Processing time (w/o IO): 17 ms
Processing time (w/o IO): 16 ms
Processing time (w/o IO): 17 ms
Processing time (w/o IO): 16 ms
Processing time (w/o IO): 16 ms
Processing time (w/o IO): 16 ms
Processing time (w/o IO): 17 ms
Processing time (w/o IO): 16 ms
Processing time (w/o IO): 16 ms
Processing time (w/o IO): 17 ms
```
after:
```
C++:
Benchmark 1: ./main
Processing time (w/o IO): 17 ms
Processing time (w/o IO): 16 ms
Processing time (w/o IO): 16 ms
Processing time (w/o IO): 17 ms
Processing time (w/o IO): 17 ms
Processing time (w/o IO): 17 ms
Processing time (w/o IO): 16 ms
Processing time (w/o IO): 17 ms
Processing …
```
=> [C++] Optimize tagMap generation.

nim_con/build.sh, nim_con/buildopt.sh, nim_con/related_con.nim, nim_con/related_con.nimble, run.sh
I found there's a modest but consistent performance improvement if I drop `xxhash` and (automatically) use Nim's default hash for `TagMap`, *and* switch back to clang.
Now, `xxhash` is definitely faster than Nim's default hash in a straight benchmark. But for this code, the combination of inlining hints, the default hash, *and* clang gives a better result.
=> [Nim Con] speedup with default hash

julia/Related/src/Related.jl
Reverts the removal by @MasonProtter in #207
Also removes trailing whitespace
=> Restore Julia's number type optimization from #171

julia/Related/src/Related.jl
Shouldn't affect runtime (at least it doesn't on my machine), just a bit more idiomatic imo
=> Slight simplification of Related.jl

julia/Related/src/Related.jl
added one(T) and zero(T) instead of 1 and 0, it was already done inside one of the loops where it counts more for performance, here I added it more for consistency, but it should be (almost **un**noticeably) faster
=> Use one(T), zero(T) instead of 1, 0 in Julia implementation

run.sh
@jinyus I saw C++ is using `-O3`, while I think we should just not use `-O3` for any language, it's your call in the end.
Meanwhile, can you kindly try `-O3` on the VM and see if it's faster or slower? I honestly don't know what to expect at this point, won't be surprised if it's actually slower, Julia's `O2` is basically always as fast.
=> [Julia] Try LLVM -O3

julia/Related/src/Related.jl, julia_con/RelatedCon/src/RelatedCon.jl, run.sh
Also removed the T, being a bit more explicit.
(the rules state that there are max 100 tags)
@Moelf
=> Hint on the number of tags in tagmap in Julia

cpp/main.cpp, run.sh
- Moved the various parts into functions to show that one doesn't have to use a single large main function.
- some small performance improvements int top5 logic by improving memory locality.
- moved to gcc & c++20 since that was the fastest after changes.
@jinyus would be curious to see how this performs on the VM.
(Tried adding better maps but only got better results when using `march=x86_64_v3` but seems like that is forbidden here from what I understand)
=> reorder to move parts into functions, switch to c++20 and gcc

go_con/main.go
Applies optimizations from #395 to go_con.
Seems to be slower...(tested twice with same results)
Main:
`Go Concurrent | 12.19 ms | 164.52 ms | 1.43 s`
This PR:
```
Go Concurrent:
Benchmark 1: ./related_concurrent
Processing time (w/o IO): 12.449775ms
Processing time (w/o IO): 14.2278ms
Processing time (w/o IO): 12.854681ms
Processing time (w/o IO): 12.754979ms
Processing time (w/o IO): 12.81938ms
Processing time (w/o IO): 12.571376ms
Processing time (w/o IO): 12.623178ms
Processing time (w/o IO): 12.324273ms
Processing time (w/o IO): 14.777608ms
Processing time (w/o IO): 12.512376ms
Processing time (w/o IO): 12.364274ms
Processing time (w/o IO): 12.278273ms
Processing time (w/o IO): 12.388574ms
Time (mean ± σ):      52.8 ms ±   1.9 ms    [User: 84.4 ms, System: 9.9 ms]
Range (min … max): …
```
=> Apply go tweaks to go_con

julia/Related/src/Related.jl, julia_con/RelatedCon/src/RelatedCon.jl, run.sh
tested on the same VM. I now suspect the vGPU has some policy if it sees you idle it will start shifting resource away from your VM or something
before:
```
Benchmark 1: julia --project=Related -e "using Related; main()"
Processing time (w/o IO): 31 milliseconds
Processing time (w/o IO): 23 milliseconds
Processing time (w/o IO): 24 milliseconds
Processing time (w/o IO): 25 milliseconds
Processing time (w/o IO): 30 milliseconds
Processing time (w/o IO): 31 milliseconds
Processing time (w/o IO): 25 milliseconds
```
after:
```
Benchmark 1: julia --project=Related -e "using Related; main()"
Processing time (w/o IO): 24 milliseconds
Processing time (w/o IO): 25 milliseconds
Processing time (w/o IO): 25 milliseconds
Processing time (w/o IO): 24 milliseconds
Processing time (w/o IO): 24 …
```
=> [Julia] Stablize the results

julia/Related/src/Related.jl, julia_con/RelatedCon/src/RelatedCon.jl
this is more accurate:
```
Processing time (w/o IO): 18.708785ms
Processing time (w/o IO): 18.180406ms
Processing time (w/o IO): 18.605787ms
Processing time (w/o IO): 17.920885000000002ms
Processing time (w/o IO): 18.325236ms
Processing time (w/o IO): 18.091424ms
Processing time (w/o IO): 18.554257ms
Processing time (w/o IO): 18.720408000000003ms
Processing time (w/o IO): 18.382645999999998ms
Processing time (w/o IO): 18.396163ms
```
before it had no decimal places
=> [julia] More accurate timings

Dockerfile, d_v2/.gitignore, d_v2/dub.json, d_v2/dub.selections.json, d_v2/source/app.d, run.sh
Added separate folder for d_v2 version. Based on SWAR optimization approach.
Added manual installation into Dockerfile - installed from official Release from LDC's GitHub page.
=> [D] Manual installation and v2 version

racket/related.rkt, run.sh
After experimentation with a more functional approach, I wasn't able to improve performance of the single-threaded Racket impl over what I achieved with `vector` and mutation — I guess it's pretty hard to beat constant time read/write afforded by `vector-ref` and `vector-set!`.
However, in the process and also while working on a Typed Racket impl (PR coming shortly) I did cleanup the code a bit.
Note: runtime numbers in the VM/Docker are pretty bouncy, probably because of Racket's garbage collector, but there's no baseline anyway so these changes are good-to-go from my perspective.
Should I add `run_racket` to `all`?
I didn't get any feedback/tips, yet, from the Racket community, but maybe someone will have ideas in the future.
=> [Racket] cleanup

Dockerfile, run.sh
This is *a* solution to the problem I realized/described [earlier today](https://github.com/jinyus/related_post_gen/pull/430#issuecomment-1811611857).
Advantages
* Having `"json-type-provider"` as a dep in `info.rkt` isn't a problem — `raco pkg install` won't be slow nor will it exit with error
* Typed Racket impl is runnable in the container, though still not included in `all` because of the slow writes
* Don't have to change anything else
* It becomes very unlikely that adding module dep/s for the Racket or Typed Racket impls (if they're to be runnable in the container) will also involve installing "missing pieces" via `pacman` and/or `raco` during `docker build`.
Disadvantages
* The size of the container increases by several hundred MB (but not a lot in the grand scheme of things). …
=> [Racket] install racket instead of racket-minimal in Docker

racket/typed/related.rkt, run.sh
I made an effort to understand *[Shallow and Optional Typed Racket](https://blog.racket-lang.org/2022/11/shallow-typed-racket.html)* and applied what I learned to the Typed Racket impl.
With the changes in e98148f I'm essentially telling the toolchain:
* Enforce static typing
* Don't do deep runtime checking for `write-json`
So, across the board, we're still getting more (type) safety than in the untyped Racket impl (else why bother with Typed Racket), but for the serialization step we're relaxing the additional runtime-soundness that comes with (Deep/default) Typed Racket, while not doing *less* "safety stuff" at runtime than untyped Racket does anyway.
I added `run_typed_racket` to `all` in run.sh since serialization is no longer a big drag on `./run.sh typed/racket`.
The extensive …
=> [Typed Racket] isolate write-json in an Optional Typed Racket submodule

run.sh
Probably it was inadvertently deleted when adding memory consumption
=> Fix JuliaCon

Dockerfile, nim/related.nimble, nim/src/related.nim
I saw the recent changes making use of a flattened list/slice and thought Nim might benefit from that as well. I also noticed the rule change in e68b47a.
The changes in this PR include building/installing the Nim compiler from its `devel` branch using [`choosenim`](https://github.com/dom96/choosenim). It's pinned to a specific commit in the Dockerfile, which can easily be updated in the future or replaced with a version such as `2.0.2` or `2.2.0` (whatever is the next stable release of v2).
With the upgraded Nim compiler, it was feasible to switch (back) to a return-values approach vs. mutating `var` parameters, with the performance being the same or a little better. Several other revisions flowed from that. 
While I was working on it, I noticed some flakiness re:
```nim
let time = …
```
=> [Nim] revise and speedup

rust/Cargo.lock, rust/Cargo.toml, rust/src/main.rs
Reverts jinyus/related_post_gen#477
https://github.com/rust-lang/hashbrown
```
SIMD lookups to scan multiple hash entries in parallel.
```
Rule violation:
https://github.com/jinyus/related_post_gen/blob/2a4eb605964a35ceaa837186867a6d9c2f8c73d0/readme.md?plain=1#L46
=> Revert "[rust] various optimizations"

run.sh
ok, it was easy. 
Looks like in new version of SBCL, also with type optimization from last commit, some data start keeping in stack (from heap), so we got stack overflow. By default it is only 2mb, now it is 10 mb
=> common-lisp stack overflow fix

clojure/src/related/core.clj
this one limits the warmup phase to 5000 posts, decreasing total run time
as an interesting consequence it also slightly speeds up larger data processing (at least on my machine)
=> clojure: limit jvm warmup phase

raw_results.md, readme.md, rust/.cargo/config.toml, rust_con/.cargo/config.toml
CPU targeting was being used; which is forbidden according to the [rules](https://github.com/jinyus/related_post_gen#no). 
Thanks to @cyrusmsk for pointing this out.
Main:
```
| Rust | 9.62 ms | 122.62 ms | 1.04 s | 1.18 s |
| Rust Concurrent | 5.27 ms | 67.41 ms | 566.25 ms | 638.94 ms |
```
This PR:
```
| Rust | 14.02 ms | 189.12 ms | 1.62 s | 1.82 s |
| Rust Concurrent | 4.66 ms | 56.88 ms | 492.16 ms | 553.71 ms |
```
=> Remove build configuration from .cargo/config.toml

ruby/related.rb
Mostly I just replaced `.each` and `.each_with_index` with `while` loop, locally it performs almost two times faster. Looks ugly but performs better :upside_down_face: 
also performance can be improved by just enabling YJIT and using `Oj` gem instead of `JSON` from std
CPU: AMD Ryzen 7 4700U
RAM: 16 GiB
Ruby: 3.3.4
Old:
```
Running ruby
Ruby:
Processing time (w/o IO): 2883ms
total: 2.99s memory: 25684k
Processing time (w/o IO): 3206ms
total: 3.31s memory: 25492k
Processing time (w/o IO): 2979ms
total: 3.08s memory: 25616k
Processing time (w/o IO): 2973ms
total: 3.07s memory: 25756k
Processing time (w/o IO): 3027ms
total: 3.13s memory: 25448k
Processing time (w/o IO): 2889ms
total: 2.99s memory: 25872k
Processing time (w/o IO): 2944ms
total: 3.05s memory: 25700k
Processing time (w/o IO): …
```
=> Ruby: uglier but faster implementation
