- go/main.go
i noticed that in go in comparison to rust a mapping was used for storing post count instead of an array which likely led to worse performance
i replaced a mapping with an array it (and also put `log.Panicln` instead of fatal log and few more fixes), i've got like 9x-ish perf boost up to 0.06s (previously was somewhat around 0.56s)
> go perf fix

- run.sh
- rust/src/main.rs
Fixes Rust max as currently there is only one rust implementation.
adds options for running go_con, python numpy.
> fix rust and bash

- jq/related.jq
- run.sh
- very slow at ~51s
- therefore not added to `./run.sh all`
> Add jq (very slow)

- python/related_duckdb.py
improves the timing calculation to be more accurate.
M2, python 3.11.4
> python duck.py 
Processing time (w/o IO): 0:00:01.629839
> more accurate timing w/o io

- dart/models.dart
- dart/related.dart
> Add type data for Dart

- rust_rayon/Cargo.lock
- rust_rayon/Cargo.toml
- rust_rayon/src/main.rs
Rayon seems to perform significantly better by only using the amount of physical cpu threads, rather than logical cpu threads
Slight improvement due to smallstr
> Cutting down the number of threads in Rayon

- raw_results.md
- readme.md
> [IGNORE] Update benchmark results

- v/related.v
This PR improves both readability and performance aspects of arrays initialization in V code.
> Improve arrays initialization in V

- raw_results.md
- readme.md
> [SKIPCI] Update benchmark results

- fsharp/Program.fs
Fixed in/out path to properly find and save json files in the root dir.
> Fixed in/out paths for fsharp

- nim/related.nimble
- nim/src/related.nim
- run.sh
Slightly better code, mostly low-hanging fruit, could definitely be optimised further. Also added LTO and PGO to the compilation which is common when going for maximum speed. Could compile with `-d:danger` for even more speed but that technically removes some bound checks and violates one of the rules. I guess `-d:danger --boundChecks:on` would still be allowed though, would give a slight increase.
> Improve Nim solution

- fsharp/Program.fs
- Used faster collections for gathering the data for Tag-Post relationships
- Switched to System.Diagnostics.Stopwatch for timing for accuracy
- Parallelized the creation of the result array
- Use stackalloc for collecting intermediate results
- Updated directory input/output to work on Windows as well
> Fsharp parallel

- zig/main.zig
This implementation reduced the time on my poor little laptop from ~300ms to ~50ms.
It basically shadows the implementation of Go but omits some trivial if statements.
I also renamed types to be UpperCase.
> Zig: Reworked zig to use a faster implementation

- nim/src/related.nim
This has three improvements:
- Uses the FxHash algorithm which is used in the Rust solution
- Performs a marginally faster zeroMem operation instead of newSeq.
- Packs the counts tighter together for faster looping by using a uint8 type
> Further speedup of Nim version

- fsharp/Program.fs
I've tried to clean up F# code a little bit (just the non-concurrent version).  
It is slightly more allocation heavy, but it also measures marginally faster on my machine.
May I ask you, if you could benchmark it, before applying this pull request.
> Make F# code a bit more idiomatic

- rust/Cargo.lock
- rust/Cargo.toml
- rust/src/main.rs
- rust_con/src/main.rs
Before
Benchmark 1: ./target/release/rust
Processing time (w/o IO): 23.382257ms
Processing time (w/o IO): 23.112573ms
Processing time (w/o IO): 23.295275ms
Processing time (w/o IO): 23.196617ms
Processing time (w/o IO): 23.227118ms
Processing time (w/o IO): 22.486412ms
Processing time (w/o IO): 22.52874ms
Processing time (w/o IO): 22.337788ms
Processing time (w/o IO): 22.548885ms
Processing time (w/o IO): 22.609888ms
Processing time (w/o IO): 22.483896ms
Processing time (w/o IO): 22.613415ms
Processing time (w/o IO): 23.129902ms
Processing time (w/o IO): 22.993105ms
Processing time (w/o IO): 22.927814ms
Time (mean ± σ):      31.4 ms ±   0.7 ms    [User: 26.4 ms, System: 4.8 ms]
Range (min … max):    30.7 ms …  32.9 ms    10 runs
After
Benchmark 1: ./target/release/rust
Processing time …
> Use Bumpalo for rust single threaded

- julia/related.jl
- run.sh
I just ran a fast experiment using `StrideArrays` - it seems to improve the GC work and has alt least 2ms impact performance on my machine.
> Perf Improvement - StrideArrays (Julia)

- csharp/Program.cs
- csharp/related.csproj
Do like Go, assume less than 100 elements.
> CSharp - Optimize Dictionaries / Enable Server GC

- csharp/Program.cs
Made code a bit more idiomatic and copied few optimizations from F# version.
> C# more tweaks and cleanup

- csharp/Program.cs
most of the time seems spent in stack pushes, could potentially get that down but would be some weird code
> C# Using Spans for better memory allocation times

- julia/related.jl
- run.sh
Reverts jinyus/related_post_gen#146
> Revert "Perf Improvement - StrideArrays (Julia)"

- julia/related.jl
@algunion my local benchmark shows
```julia
BenchmarkTools.Trial: 170 samples with 1 evaluation.
Range (min … max):  29.034 ms …  32.120 ms  ┊ GC (min … max): 0.00% … 4.70%
Time  (median):     29.381 ms               ┊ GC (median):    0.00%
Time  (mean ± σ):   29.506 ms ± 397.714 μs  ┊ GC (mean ± σ):  0.05% ± 0.44%
▃ ▁▂ ▄  █▃▂     ▁
▄▁▁█▃█████████▆▆▆█▆█▃▃▁▅▅▄▄▁▁▅▅▅▃▁▄▁▁▅▁▃▁▁▃▁▁▃▃▁▃▃▁▃▁▃▁▁▁▃▁▃ ▃
29 ms           Histogram: frequency by time         30.7 ms <
Memory estimate: 1.29 MiB, allocs estimate: 181.
```
```julia
BenchmarkTools.Trial: 257 samples with 1 evaluation.
Range (min … max):  19.041 ms …  23.469 ms  ┊ GC (min … max): 0.00% … 13.66%
Time  (median):     19.400 ms               ┊ GC (median):    0.00%
Time  (mean ± σ):   19.493 ms ± 476.229 μs  ┊ GC (mean ± σ):  0.12% ±  1.02% …
```
> [julia] add comments, reduce `getindex()` hot spot, use MVector to speed up

- julia_con/related.jl
- run.sh
This is the first attempt at a concurrent Julia version.
> Concurrent Julia - testing the waters

- zig/main.zig
> zig better top5

- zig/main.zig
sorry but memset is actually faster
> memset is faster

- Dockerfile
- d/.gitignore
- d/dub.json
- d/dub.selections.json
- d/source/app.d
- run.sh
Added D implementation based on the code from Go.
I've tested several D implementations. This one based on memutils package for HashMap, which worked a bit better than built-in Associative Arrays.
Parallel versions also under preparation, but currently they are working quite slow.
> Added D regular implementation

- crystal/src/crystal.cr
Some changes to improve performance.
> Improve Crystal

- fsharp/Program.fs
- fsharp/fsharp.fsproj
- fsharp/fsharp.rd.xml
- fsharp_con/fsharp_con.fsproj
- run.sh
https://github.com/jinyus/related_post_gen/pull/198
After C#'s upgrade to dotnet 8 & AOT, it's only fair to do the same for F#
Also, I've added ServerGarbageCollection to match C# version exactly
> Update F# to dotnet 8, add fsharp AOT version

- d/dub.json
- d/dub.selections.json
- d/source/app.d
- d_con/dub.json
- d_con/source/app.d
- run.sh
Sequential: remove a dependency for HashMap. Now it is based on built-in version
Parallel: slightly update the code that it will be inline with format of sequential version
Major part: changed the behavior of building option. Now the code use bounds-check and only "optimize" and "inline" options used in "release" mode. Previously bounds-checking were disabled by default of building in "release" mode.
Update names for output files of parallel version
> Update for D

- csharp/Program.cs
This is a pretty bad deoptimization. Seeing 68 ms on main vs 38 with this PR.
> [CSharp] Remove stackalloc

- crystal/src/crystal.cr
Recently I sent improvement with Pointer buffer usage instead of Crystal Array, but then I found out that unsafe code is against the rules. So I commented such usages in the code and added some notes in this PR.
https://crystal-lang.org/reference/latest/syntax_and_semantics/unsafe.html
> [Crystal] Revert Pointer buffer

- nim/config.nims
- nim/src/fixedtable.nim
- nim/src/related.nim
Main change is the addition `fixedtable.nim` file is just copy from the next Nim `release`. The PR is already merged: https://github.com/nim-lang/Nim/pull/22812  just to not wait until it goes into stable chain
> [Nim] fix std/table lent

- cpp/main.cpp
> [cpp] Fix #122

- raw_results.md
- readme.md
Reverts jinyus/related_post_gen#243
> Revert "[SKIP] Update Benchmark Results (Azure F4s-v2-4vCPU-8GB-RAM)"

- nim/config.nims
- nim/related.nimble
- nim/src/related.nim
- run.sh
I found that prev PR about Nim changed full structure of the nimble project. I applied some changes (which did not improve time), but to make it a bit more maintable
cc @michaelsbradleyjr
> [Nim] clang again

- go/main.go
- julia/Related/src/Related.jl
- julia_con/RelatedCon/src/RelatedCon.jl
- zig/main.zig
Checked zig, go and Julia.
Move data initialization after timer started.
> Initialization after timer

- rust/Cargo.lock
- rust/Cargo.toml
- rust/src/main.rs
- rust_con/Cargo.lock
- rust_con/Cargo.toml
- rust_con/src/main.rs
> Rust minor optimization

- nim/related.nimble
- run.sh
Looks like PGO can hit or miss collect "good" stats. 50%/50% for me.
I do not know why it is possible, but generating more stats helps (not 100%)
Here is "good" result:
> [Nim] PGO can generates bad stats. Workaround to reduce it

- d/source/app.d
- d_con/source/app.d
Optimization proposed by C++ solution
> [D] Moved from size_t(long) to int

- crystal/src/crystal.cr
More correct time measurement with small changes in hashmap init capacity.
> [Crystal] Improve time measurement

- zig/main.zig
the same patch for zig, thanks
> [zig] use u32 instead of usize

- erlang/rebar.config
- erlang/src/related_erl.app.src
- erlang/src/related_erl.erl
- run.sh
Now it's not so fast, but still.
If need add something else - just let me know
> add Erlang bench

- d/source/app.d
Reverts jinyus/related_post_gen#259
Perf regression: https://github.com/jinyus/related_post_gen/pull/275#issuecomment-1763467889
> Revert "Update app.d"

- clojure/src/related/core.clj
> [Clojure] Improvements

- d_con/source/app.d
Revert from int to size_t/ulong for concurrent version
> [D] revert type changing

- erlang/src/related_erl.erl
was 9 sec on my pc, now 3 sec.
What erlang version do you use? Use 25+ plz.
> Speedup erlang solution

- erlang/src/related_erl.erl
- run.sh
now it's 9x faster then firs version. Also, 9x more ugly))
> Erlang fixes 2

- fsharp/fsharp.fsproj
https://github.com/jinyus/related_post_gen/pull/304
As per this PR
> AOT optimize for speed for F# as in #304

- fsharp/fsharp.fsproj
Reverts jinyus/related_post_gen#309
Slower: https://github.com/jinyus/related_post_gen/pull/309#issuecomment-1766769196
> Revert "AOT optimize for speed for F# as in #304"

- fsharp/Program.fs
https://github.com/jinyus/related_post_gen/pull/304
Like in this PR, and also try to mark embedded function as inline
On my machine results are better (most of the time), needs testing from your end @jinyus if possible
> [FSharp] Utilize frozen dictionary like in C# version, make getRelated function inline

- fsharp/Program.fs
Mostly a rewrite from the new C# version introduced in #304 
AOT dropped from ~30ms to ~20ms for me
> [FSharp] Update with C# approach

- v/related.v
This PR converts `top5` and `top_posts` arrays to fixed ones since their size is always the same. This is a performance improvement because fixed arrays are always allocated on the stack.
Also, this PR changes an algorithm that calculates the top 5 posts to be equal to the F# version.
> V: improve arrays allocations

- rust_con/Cargo.lock
- rust_con/Cargo.toml
- rust_con/src/least.rs
- rust_con/src/main.rs
- rust_con/src/types.rs
- rust_con/src/utils.rs
Use least_n as an iterator
break up the single function into a main which sets up the runtime (similar to other languages which do this automatically), and allows us to only time the algorithm.
Break the types and generic re-used code into files and functions, with the intention on having this code shared between rust_con and rust solutions
> Some updates to rust_con

- dart/related.dart
> [Dart] Loops optimization

- d_con/source/app.d
Now it is produced the right answer.
Based on C# code
> [D] SIMD concurrent version

- d_con/source/app.d
Same performance. Just cleaned code after @schveiguy review
> [D] cleaned version

- csharp_con/Program.cs
Thanks to @schveiguy for this fix: #336
> [CSharp] rm redundant call to max

- run.sh
> [cpp] use clang++

- zig/fxhash.zig
- zig/main.zig
Processing time decreased about 6ms. (from 28ms to 22ms in my computer)
> port fxhash from rust to zig

- julia/Related/Project.toml
- julia/Related/src/Related.jl
Following the latest discussion in:
- https://github.com/jinyus/related_post_gen/issues/194#issuecomment-1777172218
@algunion @LilithHafner
> Try use StaticArrays.jl again for Julia

- julia/Related/src/Related.jl
for whatever reason, PrecompileTools slows things down. Also we can't use Symbol (it's not faster) anyway according to rules.
>MUST:
>Represent tags as strings
@LilithHafner @MasonProtter this is about 25% faster locally
> [Julia] go back to manual warmup and use String instead of Symbol

- julia/Related/src/Related.jl
- julia_con/RelatedCon/Project.toml
- julia_con/RelatedCon/src/RelatedCon.jl
@Moelf @MasonProtter 
50% faster on my machine
> Restore version with StaticArrays for concurrent Julia

- dascript/related.das
This is my first time using this language. I couldn't figure it out how to avoid cloning without using unsafe. So, memory usage may get high with bigger posts count.
> daScript initial implementation

- run.sh
@jinyus have you managed to build the compiler?
This PR adds daScript to `run.sh`, but I don't know how to add the compiler.
> [daScript] added to run.sh

- cpp/main.cpp
Trying to fix what was merged in #399. 
This is ~22ms locally again, hoping it works on the VM as well. 
I can gain another ~1-2ms when using mimalloc via `LD_PRELOAD`. But don't have the time right now to fiddle with getting that into this benchmark. Just mentioning it in case sombody is interested.
> fix cpp single thread version

- run.sh
> [LUAJIT] add test for juajit with -joff flag

- fsharp/Program.fs
Switch "posts" to Span instead of List (ResizeArray), seems to have better read access
Also try to fix bad IL gen for  `taggedPostCount[otherPostIdx] <- taggedPostCount[otherPostIdx] + 1uy`
Dunno if it will be actually faster on test machine.
Old:
```
// [46 17 - 46 46]
IL_0045: ldarga.s     taggedPostCount
IL_0047: ldloc.s      otherPostIdx
IL_0049: call         instance !0/*unsigned int8*/& valuetype [System.Runtime]System.Span`1<unsigned int8>::get_Item(int32)
IL_004e: stloc.s      V_8
IL_0050: ldloc.s      V_8
IL_0052: ldarga.s     taggedPostCount
IL_0054: ldloc.s      otherPostIdx
IL_0056: call         instance !0/*unsigned int8*/& valuetype [System.Runtime]System.Span`1<unsigned int8>::get_Item(int32)
IL_005b: stloc.s      V_10
IL_005d: ldloc.s      V_10
IL_005f: ldobj …
```
> [F#] Try to speedup a little

- Dockerfile
- racket/.gitignore
- racket/info.rkt
- racket/related.rkt
- run.sh
I thought it would be fun to work on another implementation besides `nim_con` and `nim`, so here's a single-threaded one in [Racket](https://racket-lang.org).
It's no speed demon, but I'll be asking the Racket community for suggestions on how to improve it. Also, I plan on doing a `racket_con` impl and variations of single and multi-threaded in [Typed Racket](https://docs.racket-lang.org/ts-reference/index.html).
> [Racket] single-threaded implementation

- Dockerfile
- lobster/json.lobster
- lobster/related.lobster
- run.sh
http://aardappel.github.io/lobster/README_FIRST.html
> Add Lobster Implementation

- go/main.go
Main:  `22.65 ms  |  322.43 ms  |  2.86 s`
This PR:
```
Go:
Benchmark 1: ./related
Processing time (w/o IO): 21.69926ms
Processing time (w/o IO): 21.683359ms
Processing time (w/o IO): 21.522457ms
Processing time (w/o IO): 21.613658ms
Processing time (w/o IO): 22.231371ms
Processing time (w/o IO): 21.630259ms
Processing time (w/o IO): 21.587957ms
Processing time (w/o IO): 22.033167ms
Processing time (w/o IO): 21.656059ms
Processing time (w/o IO): 23.635201ms
Processing time (w/o IO): 22.215771ms
Processing time (w/o IO): 21.878764ms
Processing time (w/o IO): 21.605458ms
Time (mean ± σ):      61.0 ms ±   1.4 ms    [User: 59.4 ms, System: 8.6 ms]
Range (min … max):    58.0 ms …  62.7 ms    10 runs
Go:
Benchmark 1: ./related
Processing time (w/o IO): 307.217011ms
Processing time (w/o IO): …
```
> [Go] Use flatten slice for the custom pQueue

- go_con/main.go
Main: `12.04 ms  |  165.52 ms  |  1.43 s`
This PR:
```
Go Concurrent:
Benchmark 1: ./related_concurrent
Processing time (w/o IO): 11.08487ms
Processing time (w/o IO): 12.385202ms
Processing time (w/o IO): 10.692161ms
Processing time (w/o IO): 10.65006ms
Processing time (w/o IO): 11.005468ms
Processing time (w/o IO): 10.733262ms
Processing time (w/o IO): 10.573858ms
Processing time (w/o IO): 10.744562ms
Processing time (w/o IO): 10.887066ms
Processing time (w/o IO): 10.704161ms
Processing time (w/o IO): 10.750162ms
Processing time (w/o IO): 10.731061ms
Processing time (w/o IO): 10.704761ms
Time (mean ± σ):      48.6 ms ±   0.8 ms    [User: 73.9 ms, System: 10.3 ms]
Range (min … max):    47.2 ms …  50.0 ms    10 runs
Go Concurrent:
Benchmark 1: ./related_concurrent
Processing time (w/o IO): …
```
> [GO Concurrent] Use flattened slice

- v/related.v
Main: `48.82 ms  |  743.93 ms |  6.60 s`
This PR:
```
Vlang:
Benchmark 1: ./related
Processing time (w/o IO): 23.351ms
Processing time (w/o IO): 26.541ms
Processing time (w/o IO): 24.216ms
Processing time (w/o IO): 23.916ms
Processing time (w/o IO): 23.535ms
Processing time (w/o IO): 24.046ms
Processing time (w/o IO): 23.858ms
Processing time (w/o IO): 24.002ms
Processing time (w/o IO): 23.984ms
Processing time (w/o IO): 24.424ms
Processing time (w/o IO): 23.227ms
Processing time (w/o IO): 24.020ms
Processing time (w/o IO): 23.963ms
Time (mean ± σ):     328.5 ms ±   3.5 ms    [User: 305.5 ms, System: 22.7 ms]
Range (min … max):   323.2 ms … 333.3 ms    10 runs
Vlang:
Benchmark 1: ./related
Processing time (w/o IO): 357.253ms
Processing time (w/o IO): 355.159ms
Processing time (w/o IO): …
```
> [V] Use flattened slice

- rust/src/main.rs
Main: `| 23.60 ms  | 341.14 ms  | 3.05 s `
This PR:
```
Rust:
Benchmark 1: ./target/release/rust
Processing time (w/o IO): 21.976574ms
Processing time (w/o IO): 22.039975ms
Processing time (w/o IO): 21.961573ms
Processing time (w/o IO): 21.942074ms
Processing time (w/o IO): 21.971674ms
Processing time (w/o IO): 21.965574ms
Processing time (w/o IO): 22.814792ms
Processing time (w/o IO): 22.23478ms
Processing time (w/o IO): 23.252801ms
Processing time (w/o IO): 21.891372ms
Processing time (w/o IO): 22.029076ms
Processing time (w/o IO): 22.067376ms
Processing time (w/o IO): 21.951973ms
Time (mean ± σ):      36.8 ms ±   1.6 ms    [User: 31.4 ms, System: 5.3 ms]
Range (min … max):    35.4 ms …  39.9 ms    10 runs
Rust:
Benchmark 1: ./target/release/rust
Processing time (w/o IO): 319.851499ms …
```
> [Rust] Use flattened list

- extract_results.dart
- run.sh
> Add chart with memory usage

- rust/src/main.rs
Could you give this a spin? I see a 4% improvement on my bare-metal machine, but not sure how well this performs in an Azure VM.
> [rust] Functional rewrite of top5 extraction

- swift/Sources/main.swift
Not much differece...
Main: ` 52.34 ms | 725.63 ms | 6.23 s`
This PR:
```
Swift:
Processing time (w/o IO): 51.10597610473633ms
total: 0.44s memory: 77376k
Processing time (w/o IO): 51.303982734680176ms
total: 0.45s memory: 76664k
Processing time (w/o IO): 51.55599117279053ms
total: 0.45s memory: 76740k
Processing time (w/o IO): 52.25801467895508ms
total: 0.44s memory: 77232k
Processing time (w/o IO): 51.16891860961914ms
total: 0.45s memory: 76712k
Processing time (w/o IO): 51.73301696777344ms
total: 0.45s memory: 77020k
Processing time (w/o IO): 50.8270263671875ms
total: 0.44s memory: 76848k
Processing time (w/o IO): 52.11794376373291ms
total: 0.44s memory: 76780k
Processing time (w/o IO): 51.35798454284668ms
total: 0.44s memory: 76796k
Processing time (w/o IO): 51.55503749847412ms
total: …
```
> [Swift] Use flattened list

- go/main.go
Main: `19.10 ms | 282.11 ms | 2.48 s `
This PR:
```
Go:
Processing time (w/o IO): 19.31218ms
total: 0.04s memory: 13128k
Processing time (w/o IO): 18.959362ms
total: 0.04s memory: 12996k
Processing time (w/o IO): 18.944572ms
total: 0.04s memory: 13128k
Processing time (w/o IO): 19.166462ms
total: 0.04s memory: 13052k
Processing time (w/o IO): 19.235371ms
total: 0.04s memory: 13004k
Processing time (w/o IO): 18.955822ms
total: 0.04s memory: 13512k
Processing time (w/o IO): 19.24913ms
total: 0.04s memory: 13168k
Processing time (w/o IO): 19.026742ms
total: 0.04s memory: 13012k
Processing time (w/o IO): 19.054162ms
total: 0.04s memory: 13008k
Processing time (w/o IO): 19.18756ms
total: 0.04s memory: 13008k
Go:
Processing time (w/o IO): 279.608796ms
total: 0.39s memory: 44436k
Processing time …
```
> [Go] Zero out the slice at the end of the hot loop

- d_v2/source/app.d
Updated mono core chunked version
> [D] Chunked version update

- nim/src/related.nim
These changes shouldn't affect performance, but it seemed like a good idea to submit them in a separate PR.
> [Nim] cleanup time formatting

- ocaml/bin/main.ml
Just couple of small optimizations:
- Initialize taggetPostCount array outside of a loop
- Calculate posts length just once outside of a loop
> [OCaml] Optimizations

- rust/Cargo.lock
- rust/Cargo.toml
- rust/src/main.rs
* Drop bumpalo and mimalloc in favor an aligned vec.
* Use hashbrown instead of std+fxhasher.
> [rust] various optimizations

- rust/Cargo.lock
- rust/Cargo.toml
- rust/src/main.rs
* Drop bumpalo and mimalloc in favor an aligned vec.
* Use AHash instead of FxHash.
Like #477, but without hashbrown.
> [rust] various optimizations #2

- Dockerfile
- d_v2/source/app.d
PR prepared by Bruce Carneal.
Some code separation: added @safe part.
Also I've added LDC 1.36-beta1 in the Dockerfile
> [D] @safe optimization

- Dockerfile
main: `34.58 ms | 394.38 ms | 3.46 s`
This PR:
```
Odin:
Processing time (w/o IO):  27.817399ms
total: 0.20s memory: 13184k
Processing time (w/o IO):  28.03395ms
total: 0.24s memory: 13184k
Processing time (w/o IO):  27.510068ms
total: 0.20s memory: 13184k
Processing time (w/o IO):  27.741689ms
total: 0.20s memory: 13056k
Processing time (w/o IO):  27.790649ms
total: 0.20s memory: 13184k
Processing time (w/o IO):  28.57278ms
total: 0.20s memory: 13184k
Processing time (w/o IO):  27.936029ms
total: 0.20s memory: 13312k
Processing time (w/o IO):  27.862619ms
total: 0.20s memory: 13312k
Processing time (w/o IO):  28.002819ms
total: 0.20s memory: 13184k
Processing time (w/o IO):  27.692328ms
total: 0.20s memory: 13184k
Odin:
Processing time (w/o IO):  397.442644ms
total: 1.08s memory: 44160k …
```
> Update odin compiler

- common-lisp/related.lisp
Added proper type hints for the compiler, doubling performance w/o IO, and roughly 1.5x performance with io
> add proper type hints for performance

- raw_results.md
- readme.md
by @NoobsEnslaver and @leetwinski
> Add common lisp results

- rust/.cargo/config.toml
- rust/Cargo.lock
- rust/Cargo.toml
- rust/src/main.rs
- rust_con/.cargo/config.toml
- rust_con/Cargo.lock
- rust_con/Cargo.toml
- rust_con/src/main.rs
I updated dependencies, cleaned up some code and most importantly: I improved the overall performance by writing JSON directly into the output file.
> Rust polish

- clojure/src/related/core.clj
rearranged code, updated type hints, 
(fixed insane code formatting)
added jvm warmup
speedup on my machine ~1.5s -> ~150ms
> clojure code rearrange and speedup

- common-lisp/related.lisp
update post representation to struct
~20% speedup on my machine
> common lisp: change post representation data structure

- Dockerfile
- raw_results.md
- readme.md
Main:
```
| D | 18.38 ms | 242.14 ms | 2.03 s | 2.29 s |
```
This PR:
```
| D | 18.61 ms | 239.68 ms | 2.04 s | 2.30 s |
```
> update ldc to 2.36.0 with results

- raw_results.md
- readme.md
Main:
```
| D (v2) | 11.58 ms | 120.52 ms | 948.58 ms | 1.08 s |
| D Concurrent | 7.10 ms | 61.73 ms | 453.57 ms | 522.41 ms |
```
This PR:
```
| D (v2) | 11.46 ms | 118.74 ms | 943.36 ms | 1.07 s |
| D Concurrent | 7.09 ms | 61.79 ms | 452.55 ms | 521.43 ms |
```
> update dv2 and d_con results

- cpp/main.cpp
- cpp/main_con.cpp
- run.sh
- zig/main.zig
not necessarily faster, addresses the concern of bare pointer
> cpp and cpp_con ref #410 and zig improvement

- run.sh
- zig_con/main.zig
> Zig Concurrent solution

- raw_results.md
- readme.md
- run.sh
Thanks for pointing this out.
@thelissimus
> Add haskell to results table and all runner

- Dockerfile
I would be interested to see if this makes a difference, it should be faster than 1.9
> Update Julia to 1.11

- dockerfiles/haskell.Dockerfile
- dockerfiles/julia.Dockerfile
- dockerfiles/ruby.Dockerfile
This is only done to make it easier/faster to update results of a single language. I usually pull the main docker image from github but it can take up to 15mins to download and extract; using these smaller images makes this process much faster.
> Add dockerfile for each language

- inko/src/main.inko
**NOTE:** Inko 0.17.0 isn't released yet, I've simply set up this PR ahead of time so I won't forget about it later :smiley: 
This updates the Inko implementation for the 0.17.0 release.
> Update Inko for 0.17.0

- run.sh
The `time` command on MacOS doesn't have -f flag, fixing run.sh to require the gnu-time binary.
> Fix run.sh to run on MacOS
